/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_jonrryenamorado;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author wende
 */
public class principal extends javax.swing.JFrame {

    
        

    /**
     * Creates new form principal
     */
    String codigo;
        double edad;
        double peso = 0;
        double pcriaturas = 0;

    

    public principal() {
        try{
        codigo = JOptionPane.showInputDialog("Ingrese el codigo de su universo");
        edad = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la edad"));
        initComponents();
        JOptionPane.showMessageDialog(rootPane, "BIENVENIDO AL UNIVERSO TALI! ERES UN DIOS Y ESTE UNIVERSO, EL MAS HERMOSO UNIVERSO, FUE PUESTO EN"
                + " TUS MANOS PARA CREAR MUNDOS Y CRIATURAS.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_cc = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_raza = new javax.swing.JTextField();
        jtf_energia = new javax.swing.JTextField();
        jtf_maños = new javax.swing.JTextField();
        jtf_region = new javax.swing.JTextField();
        jtf_cant = new javax.swing.JTextField();
        jtf_objetos = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtf_pesocriatura = new javax.swing.JTextField();
        jd_cm = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jtf_mundoname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jtf_pesomundo = new javax.swing.JTextField();
        jd_eu = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtf_cod = new javax.swing.JTextField();
        jtf_edaduni = new javax.swing.JTextField();
        jtf_pesouni = new javax.swing.JTextField();
        popupmundo = new javax.swing.JPopupMenu();
        agregar = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        popupmundo1 = new javax.swing.JPopupMenu();
        agregar1 = new javax.swing.JMenuItem();
        popupcriatura = new javax.swing.JPopupMenu();
        agregarcr = new javax.swing.JMenuItem();
        modificarcr1 = new javax.swing.JMenuItem();
        eliminarcr = new javax.swing.JMenuItem();
        popupcriatura1 = new javax.swing.JPopupMenu();
        agregarcr1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_criaturas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_mundos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_universo = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel3.setText("El todo poderoso a decidido crear una criatura");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Nueva Criatura");

        jLabel5.setText("Raza:");

        jLabel6.setText("Energía:");

        jLabel7.setText("Max. Años:");

        jLabel8.setText("Region:");

        jLabel9.setText("Cantidad Viva: ");

        jLabel10.setText("Objetos:");

        jtf_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_regionActionPerformed(evt);
            }
        });

        jButton5.setText("Crear Criatura");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel11.setText("Peso:");

        javax.swing.GroupLayout jd_ccLayout = new javax.swing.GroupLayout(jd_cc.getContentPane());
        jd_cc.getContentPane().setLayout(jd_ccLayout);
        jd_ccLayout.setHorizontalGroup(
            jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ccLayout.createSequentialGroup()
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ccLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_energia, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jtf_maños)
                            .addComponent(jtf_region)
                            .addComponent(jtf_cant)
                            .addComponent(jtf_pesocriatura)
                            .addComponent(jtf_objetos)))
                    .addGroup(jd_ccLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel4))
                    .addGroup(jd_ccLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel3))
                    .addGroup(jd_ccLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ccLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton5)))
                .addGap(150, 150, 150))
        );
        jd_ccLayout.setVerticalGroup(
            jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ccLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_maños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_pesocriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jLabel13.setText("Peso:");

        jLabel14.setText("El todo poderoso a decidido crear un Mundo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Nuevo Mundo");

        jLabel16.setText("Nombre:");

        jButton6.setText("Crear Mundo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_cmLayout = new javax.swing.GroupLayout(jd_cm.getContentPane());
        jd_cm.getContentPane().setLayout(jd_cmLayout);
        jd_cmLayout.setHorizontalGroup(
            jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cmLayout.createSequentialGroup()
                .addGroup(jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cmLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel15))
                    .addGroup(jd_cmLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton6))
                    .addGroup(jd_cmLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel14))
                    .addGroup(jd_cmLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_mundoname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_pesomundo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jd_cmLayout.setVerticalGroup(
            jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cmLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_mundoname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jd_cmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_pesomundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(23, 23, 23))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Universo Tali");

        jLabel17.setText("Codigo:");

        jLabel18.setText("Edad:");

        jLabel19.setText("Peso:");

        jtf_cod.setEditable(false);
        jtf_cod.setText(codigo);
        jtf_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codActionPerformed(evt);
            }
        });

        jtf_edaduni.setEditable(false);
        jtf_edaduni.setText(Double.toString(edad)
        );

        jtf_pesouni.setEditable(false);
        jtf_pesouni.setText(Double.toString(peso)
        );

        javax.swing.GroupLayout jd_euLayout = new javax.swing.GroupLayout(jd_eu.getContentPane());
        jd_eu.getContentPane().setLayout(jd_euLayout);
        jd_euLayout.setHorizontalGroup(
            jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_euLayout.createSequentialGroup()
                .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_euLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_euLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(27, 27, 27)
                        .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_euLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_euLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jtf_edaduni))
                            .addComponent(jtf_pesouni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jd_euLayout.setVerticalGroup(
            jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_euLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(42, 42, 42)
                .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtf_edaduni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_euLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtf_pesouni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        agregar.setText("agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        popupmundo.add(agregar);

        modificar.setText("modifcar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        popupmundo.add(modificar);

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        popupmundo.add(eliminar);

        agregar1.setText("agregar");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });
        popupmundo1.add(agregar1);

        agregarcr.setText("agregar");
        agregarcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcrActionPerformed(evt);
            }
        });
        popupcriatura.add(agregarcr);

        modificarcr1.setText("modificar");
        modificarcr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarcr1ActionPerformed(evt);
            }
        });
        popupcriatura.add(modificarcr1);

        eliminarcr.setText("eliminar");
        popupcriatura.add(eliminarcr);

        agregarcr1.setText("agregar");
        agregarcr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcr1ActionPerformed(evt);
            }
        });
        popupcriatura1.add(agregarcr1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("El Universo Que Te Ama");

        jl_criaturas.setModel(new DefaultListModel());
        jl_criaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_criaturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_criaturas);

        jl_mundos.setModel(new DefaultListModel());
        jl_mundos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mundosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_mundos);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Universo Tali");
        jt_universo.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_universo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_universoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_universo);

        jLabel2.setText("Bienvenido dios, ¿Qué desea realizar?");

        jButton1.setText("Crear Mundo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Criatura");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Datos Universo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Meter a Universo");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(76, 76, 76)
                        .addComponent(jButton2)
                        .addGap(63, 63, 63)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
        jd_cm.setModal(true);
        jd_cm.pack();
        jd_cm.setLocationRelativeTo(this);
        jd_cm.setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try{
        jd_cc.setModal(true);
        jd_cc.pack();
        jd_cc.setLocationRelativeTo(this);
        jd_cc.setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try{
        jtf_pesouni.setText(Double.toString(peso));
        jd_eu.setModal(true);
        jd_eu.pack();
        jd_eu.setLocationRelativeTo(this);
        jd_eu.setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_jButton3MouseClicked
    private String[] objetos(String x) {
        
        String tokens[] = x.split(",");
        return tokens;
    }
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try{
        DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        String objetos[] = objetos(jtf_objetos.getText());
        if ((Double.parseDouble(jtf_cant.getText()) < 0) || (Double.parseDouble(jtf_maños.getText()) < 1) || (Double.parseDouble(jtf_pesocriatura.getText()) < 1)) {
            JOptionPane.showMessageDialog(jd_cc, "DATO NO VALIDO VUELVA A METER ESO");
        } else {
            modelo.addElement(new Criaturas(jtf_raza.getText(), (double) Integer.parseInt(jtf_energia.getText()),
                    (double) Integer.parseInt(jtf_maños.getText()),
                    jtf_region.getText(), (double) Integer.parseInt(jtf_cant.getText()), objetos, (double) Integer.parseInt(jtf_pesocriatura.getText())));
            jl_criaturas.setModel(modelo);

            jd_cc.dispose();
            jtf_cant.setText("");
            jtf_raza.setText("");
            jtf_energia.setText("");
            jtf_maños.setText("");
            jtf_region.setText("");
        }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jtf_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_regionActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try{
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        if (Double.parseDouble(jtf_pesomundo.getText()) < 1) {
            JOptionPane.showMessageDialog(jd_cm, "ERROR META ESOS DATOS BIEN");
        } else {

            modelo.addElement(new Mundos(jtf_mundoname.getText(), (double) Integer.parseInt(jtf_pesomundo.getText())));
            jl_mundos.setModel(modelo);

            jtf_mundoname.setText("");
            jtf_pesomundo.setText("");
            jd_cm.dispose();
        }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jtf_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try{
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_universo.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        DefaultListModel modeloMUNDO = (DefaultListModel) jl_mundos.getModel();
        DefaultListModel modeloCRIATURA = (DefaultListModel) jl_criaturas.getModel();
        String mundo = "k", criatura;
        Mundos mundo1 = new Mundos();
        //selectedElement.getLastPathComponent().getUserObject() instanceof Mundos)
        TreePath selectedElement
                = (TreePath) jt_universo.getSelectionPath();

        boolean hacer = true;
        boolean delmundo = false;

        if (selectedElement != null && jl_criaturas.getSelectedIndex() >= 0 && jl_mundos.getSelectedIndex() < 0) {
            DefaultMutableTreeNode tmp = (DefaultMutableTreeNode) selectedElement.getLastPathComponent();
            if ((jl_mundos.getSelectedIndex() == -1) && (tmp.getUserObject() instanceof Mundos)) {
                mundo = tmp.getUserObject().toString();
                System.out.println(mundo);
                mundo1 = (Mundos) modeloMUNDO.get(jl_mundos.getSelectedIndex());

            }
        } else if ((jl_mundos.getSelectedIndex() >= 0 && jl_criaturas.getSelectedIndex() >= 0 && selectedElement == null)) {
            mundo = ((Mundos) modeloMUNDO.get(jl_mundos.getSelectedIndex())).getName();
            delmundo = true;
        } else {
            JOptionPane.showMessageDialog(this, "ERROR SELECCIONE SOLO LA CRIATURA Y UN MUNDO AL CUAL AGREGAR");
            jl_mundos.setSelectedIndex(-1);
            jl_criaturas.setSelectedIndex(-1);
            jt_universo.setSelectionPath(null);
            hacer = false;
        }
        criatura = ((Criaturas) modeloCRIATURA.get(jl_criaturas.getSelectedIndex())).getRaza();

        if (hacer) {
            int centinela = -1;
            boolean rep = false;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().equals(mundo)) {

                    for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                        if (raiz.getChildAt(i).getChildAt(j).toString().equals(criatura)) {
                            rep = true;
                        }
                    }
                    if (!rep) {
                        Criaturas tmp = ((Criaturas) modeloCRIATURA.get(jl_criaturas.getSelectedIndex()));
                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(((Criaturas) modeloCRIATURA.get(jl_criaturas.getSelectedIndex())));
                        ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        peso += tmp.getPeso() * tmp.getCantidad();
                    } else {
                        JOptionPane.showMessageDialog(this, "CRIATURA YA ESTA EN ARBOL");
                    }

                    centinela = 1;
                }
            }
            if (centinela == -1) {
                Criaturas tmp = ((Criaturas) modeloCRIATURA.get(jl_criaturas.getSelectedIndex()));
                peso += tmp.getPeso() * tmp.getCantidad();
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(mundo);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(((Criaturas) modeloCRIATURA.get(jl_criaturas.getSelectedIndex())));
                peso += mundo1.getPeso();
                n.add(p);
                raiz.add(n);
            }
            modeloARBOL.reload();
            modeloCRIATURA.remove(jl_criaturas.getSelectedIndex());
            if (delmundo) {
                modeloMUNDO.remove(jl_mundos.getSelectedIndex());
            }

        }
        jl_mundos.setSelectedIndex(-1);
        jl_criaturas.setSelectedIndex(-1);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jl_criaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_criaturasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown() && jl_criaturas.getSelectedIndex() < 0) {
            popupcriatura1.show(evt.getComponent(), evt.getX(), evt.getY());

        }
        if (evt.isMetaDown() && jl_criaturas.getSelectedIndex() >= 0) {
            popupcriatura.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jl_criaturasMouseClicked

    private void jl_mundosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mundosMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown() && jl_mundos.getSelectedIndex() < 0) {
            popupmundo1.show(evt.getComponent(), evt.getX(), evt.getY());

        }
        if (evt.isMetaDown() && jl_mundos.getSelectedIndex() >= 0) {
            popupmundo.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jl_mundosMouseClicked

    private void jt_universoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_universoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jt_universoMouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        jd_cm.setModal(true);
        jd_cm.pack();
        jd_cm.setLocationRelativeTo(this);
        jd_cm.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        // TODO add your handling code here:
        jd_cm.setModal(true);
        jd_cm.pack();
        jd_cm.setLocationRelativeTo(this);
        jd_cm.setVisible(true);
    }//GEN-LAST:event_agregar1ActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        try{
        DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
        String name = JOptionPane.showInputDialog("Ingrese nuevo nombre");
        boolean ver = false;
        Mundos temp = (Mundos) modelo.getElementAt(jl_mundos.getSelectedIndex());
        for (int i = 0; i < modelo.getSize(); i++) {
            if ((((Mundos) modelo.get(i)).getName().equals(name))) {
                ver = true;
            }
        }
        if (!ver) {
            temp.setName(name);
            modelo.setElementAt(temp, jl_mundos.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(this, "MUNDO YA ESTA EN LISTA");
        }
        jl_mundos.setModel(modelo);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }


    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jl_mundos.getModel();
        model.remove(jl_mundos.getSelectedIndex());
    }//GEN-LAST:event_eliminarActionPerformed

    private void agregarcr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcr1ActionPerformed
        // TODO add your handling code here:
        jd_cc.setModal(true);
        jd_cc.pack();
        jd_cc.setLocationRelativeTo(this);
        jd_cc.setVisible(true);
    }//GEN-LAST:event_agregarcr1ActionPerformed

    private void agregarcrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcrActionPerformed
        // TODO add your handling code here:
        jd_cc.setModal(true);
        jd_cc.pack();
        jd_cc.setLocationRelativeTo(this);
        jd_cc.setVisible(true);
    }//GEN-LAST:event_agregarcrActionPerformed

    private void modificarcr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarcr1ActionPerformed
        // TODO add your handling code here:
        try{
        DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
        String name = JOptionPane.showInputDialog("Ingrese nuevo nombre");
        boolean ver = false;
        Criaturas temp = (Criaturas) modelo.getElementAt(jl_criaturas.getSelectedIndex());
        for (int i = 0; i < modelo.getSize(); i++) {
            if ((((Criaturas) modelo.get(i)).getRaza().equals(name))) {
                ver = true;
            }
        }
        if (!ver) {
            temp.setRaza(name);
            modelo.setElementAt(temp, jl_criaturas.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(this, "CRIATURA YA ESTA EN LISTA");
        }
        jl_criaturas.setModel(modelo);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR METISTE LA PATA");
        }
    }//GEN-LAST:event_modificarcr1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenuItem agregar1;
    private javax.swing.JMenuItem agregarcr;
    private javax.swing.JMenuItem agregarcr1;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JMenuItem eliminarcr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_cc;
    private javax.swing.JDialog jd_cm;
    private javax.swing.JDialog jd_eu;
    private javax.swing.JList<String> jl_criaturas;
    private javax.swing.JList<String> jl_mundos;
    private javax.swing.JTree jt_universo;
    private javax.swing.JTextField jtf_cant;
    private javax.swing.JTextField jtf_cod;
    private javax.swing.JTextField jtf_edaduni;
    private javax.swing.JTextField jtf_energia;
    private javax.swing.JTextField jtf_maños;
    private javax.swing.JTextField jtf_mundoname;
    private javax.swing.JTextField jtf_objetos;
    private javax.swing.JTextField jtf_pesocriatura;
    private javax.swing.JTextField jtf_pesomundo;
    private javax.swing.JTextField jtf_pesouni;
    private javax.swing.JTextField jtf_raza;
    private javax.swing.JTextField jtf_region;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem modificarcr1;
    private javax.swing.JPopupMenu popupcriatura;
    private javax.swing.JPopupMenu popupcriatura1;
    private javax.swing.JPopupMenu popupmundo;
    private javax.swing.JPopupMenu popupmundo1;
    // End of variables declaration//GEN-END:variables

    Criaturas criatura_seleccionada;
    DefaultMutableTreeNode nodo_seleccionado;

}
